export const CONSTANT_NEW = 'FILTER_NEW';
export const CONSTANT_PARTY = 'FILTER_PARTY';
export const CONSTANT_EVENTS = 'FILTER_EVENTS';
export const CONSTANT_OLD = 'FILTER_OLD';
export const CONSTANT_WEDDING = 'FILTER_WEDDING';
export const CONSTANT_PORTRAITS = 'FILTER_PORTRAITS';
export const ACTION_TYPE_FILTER = 'ACTION_TYPE_FILTER';